function print_parameters(time_now,...
    folder_info,...
    sample_material,...
    laser_amp_percentage,...
    laser_power,...
    laser_steps,...
    laser_rep_rate,...
    ref_freq,...
    time_constant,...
    roll_off,...
    sensitivity,...
    sweeps,...
    no_of_data_points,...
    background,...
    current_humidity,...
    humidity,...
    time_taken_for_measurement_mins,...
    comments)

%% data types
%   only ustep_size, sweeps, no_of_data_points, time_taken_for_measurement_mins...
%   are numeric; all others are string

file_name_parameters =  strcat(time_now,'_',sample_material,'_parameters','.txt'); % simplified
file_info = fullfile(folder_info,file_name_parameters);

%file id
fid = fopen(file_info, 'wt');

%print text
fprintf(fid,['Sample:\t\t\t %s\n',...
              'Laser Amp Percentage:\t %s\n',...
              'Laser Power:\t\t %s\n',...
              'Laser Compressor:\t %s\n',...
              'Laser Rep Rate:\t\t %s\n',...
              'Lock-In Ref Freq:\t %s\n',...
              'Lock-In Time Constant:\t %s\n',...
              'Lock-In Roll off\t %s\n',...
              'Lock-In Sensitivity:\t %s\n',...
              'Forward_sweeps:\t\t %d\n',...
              'Number_of_data_points:\t %d\n',...
              'Background offset:\t %4.2f\n',...
              'Current humidity:\t %4.2f  \n'...
              'Humidity limit:\t\t %4.2f  \n',...
              'Scan time:\t\t %4.2f\n',...
              'Comments:\t\t %s\n'],...             
               sample_material,...
               laser_amp_percentage,...
               laser_power,...
               laser_steps,...
               laser_rep_rate,...
               ref_freq,...
               time_constant,...
               roll_off,...
               sensitivity,...
               sweeps,...
               no_of_data_points,...
               background,...
               current_humidity,...
               humidity,...
               time_taken_for_measurement_mins,...
               comments);


% close file
fclose(fid);
















end